tasks = [
    [tc.PowerCycleTelecommand(1), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(2), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(3), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(4), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(5), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(6), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(7), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(8), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(9), Send, WaitMode.NoWait],
    [2, Sleep, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(10), Send, WaitMode.NoWait],
    [20, Sleep, WaitMode.NoWait],
    [[tc.SendBeacon(), 15], SendLoop, WaitMode.NoWait],
]
