tasks = [[tc.SetBitrate(67, 8), Send, WaitMode.Wait],
[tc.SetBitrate(63, 8), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.ListFiles(64, '/'), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(65, '/suns', [i for i in range(0, 25, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(66, '/suns', [i for i in range(25, 50, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(67, '/suns', [i for i in range(50, 75, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(68, '/suns', [i for i in range(75, 100, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(69, '/suns', [i for i in range(100, 25, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(70, '/suns', [i for i in range(125, 150, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(71, '/suns', [i for i in range(150, 175, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(72, '/suns', [i for i in range(175, 200, 1)]), Send, WaitMode.Wait],
[tc.DownloadFile(73, '/suns', [i for i in range(200, 225, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(74, '/suns', [i for i in range(225, 250, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(75, '/suns', [i for i in range(250, 275, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(76, '/suns', [i for i in range(275, 300, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(77, '/suns', [i for i in range(300, 325, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(78, '/suns', [i for i in range(325, 350, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(79, '/suns', [i for i in range(350, 375, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(80, '/suns', [i for i in range(375, 400, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(81, '/suns', [i for i in range(400, 425, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(82, '/suns', [i for i in range(425, 450, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(83, '/suns', [i for i in range(450, 475, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(84, '/suns', [i for i in range(475, 500, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(85, '/suns', [i for i in range(500, 525, 1)]), Send, WaitMode.Wait],
[tc.DownloadFile(86, '/suns', [i for i in range(525, 550, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(87, '/suns', [i for i in range(550, 575, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(88, '/suns', [i for i in range(575, 600, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(89, '/suns', [i for i in range(600, 625, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(90, '/suns', [i for i in range(625, 650, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(91, '/suns', [i for i in range(650, 675, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(92, '/suns', [i for i in range(675, 700, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(93, '/suns', [i for i in range(700, 725, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(94, '/suns', [i for i in range(725, 750, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(95, '/suns', [i for i in range(750, 775, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(96, '/suns', [i for i in range(775, 800, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(97, '/suns', [i for i in range(800, 825, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(98, '/suns', [i for i in range(825, 834, 1)]), Send, WaitMode.NoWait],
]
