tasks = [[tc.SetBitrate(50, 8), Send, WaitMode.Wait],
[tc.SetBitrate(51, 8), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.ListFiles(52, '/'), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.RemoveFile(49, '/p1_8'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_9'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_10'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_11'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_12'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_13'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_14'), Send, WaitMode.NoWait],
[tc.RemoveFile(49, '/p1_15'), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.ListFiles(53, '/'), Send, WaitMode.Wait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(54, '/p2_0', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(55, '/p2_0', [i for i in range(20, 47, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(56, '/p2_1', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(57, '/p2_1', [i for i in range(20, 48, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(58, '/p2_2', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(59, '/p2_2', [i for i in range(20, 47, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(60, '/p2_3', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(61, '/p2_3', [i for i in range(20, 46, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(62, '/p2_4', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(63, '/p2_4', [i for i in range(20, 46, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(64, '/p2_5', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(65, '/p2_5', [i for i in range(20, 47, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(66, '/p2_6', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(67, '/p2_6', [i for i in range(20, 48, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
[tc.DownloadFile(68, '/p2_7', [i for i in range(0, 20, 1)]), Send, WaitMode.NoWait],
[tc.DownloadFile(69, '/p2_7', [i for i in range(20, 48, 1)]), Send, WaitMode.NoWait],
[tc.SendBeacon(), Send, WaitMode.Wait],
]
