tasks = [
    [tc.AbortExperiment(1), SendReceive, WaitMode.NoWait],
    [tc.AbortExperiment(1), Send, WaitMode.Wait],
    [tc.DisableOverheatSubmode(2, 0), SendReceive, WaitMode.NoWait],
    [tc.DisableOverheatSubmode(2, 1), Send, WaitMode.Wait],
    [tc.DisableOverheatSubmode(2, 2), Send, WaitMode.NoWait],
    [tc.EnterIdleState(3, 0), Send, WaitMode.NoWait],
    [tc.EnterIdleState(3, 100), Send, WaitMode.NoWait],
    [tc.EnterIdleState(3, 101), Send, WaitMode.NoWait],
    [tc.EraseBootTableEntry([]), Send, WaitMode.NoWait],
    [tc.EraseBootTableEntry([0, 1, 2, 2]), Send, WaitMode.NoWait],
    [tc.EraseBootTableEntry([1, 3]), Send, WaitMode.NoWait],
    [tc.EraseBootTableEntry([6]), Send, WaitMode.NoWait],
    [tc.EraseBootTableEntry([0, 1, 2, 3, 4, 5, 6]), Send, WaitMode.NoWait],
    [tc.GetCompileInfoTelecommand(), Send, WaitMode.NoWait],
    [tc.GetErrorCounterConfig(), Send, WaitMode.NoWait],
    [tc.GetPersistentState(), Send, WaitMode.NoWait],
    [tc.ListFiles(5, ""), Send, WaitMode.NoWait],
    [tc.ListFiles(5, "/abcd"), Send, WaitMode.NoWait],
    [tc.ListFiles(5, "/012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678912"), Send, WaitMode.NoWait],
    [tc.ListFiles(5, "/0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789123"), Send, WaitMode.NoWait],
    [tc.OpenSailTelecommand(11,True), Send, WaitMode.NoWait],
    [tc.PerformPayloadCommissioningExperiment(20, "/path"), Send, WaitMode.NoWait],
    [tc.PerformPayloadCommissioningExperiment(20, "/1234567890123456789012345678"), Send, WaitMode.NoWait],
    [tc.PerformPayloadCommissioningExperiment(20, "/12345678901234567890123456789"), Send, WaitMode.NoWait],
    [tc.PerformPayloadCommissioningExperiment(20, ""), Send, WaitMode.NoWait],
    [tc.PerformRadFETExperiment(20, 1, 2, '/abc'), Send, WaitMode.NoWait],
    [tc.PerformRadFETExperiment(20, 1, 2, '/1234567890123456789012345678'), Send, WaitMode.NoWait],
    [tc.PerformRadFETExperiment(20, 1, 2, '/12345678901234567890123456789'), Send, WaitMode.NoWait],
    [tc.PerformRadFETExperiment(20, 1, 2, ''), Send, WaitMode.NoWait],
    [tc.PerformSailExperiment(21), Send, WaitMode.NoWait],
    [tc.PingTelecommand(), Send, WaitMode.NoWait],
    [tc.PowerCycleTelecommand(11), Send, WaitMode.NoWait],
    [tc.PurgePhotoTelecommand(11), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 49, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 2, 80, 200, []), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 2, 80, 200, [i for i in range(0, 190, 1)]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 2, 80, 200, [i for i in range(0, 191, 1)]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 0, 0x10, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 0, 0x31, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 0, 0x35, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 0, 0x60, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 0, 0x61, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 0x30, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 0x32, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 0x36, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 0x44, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 0x51, 200, [1]), Send, WaitMode.NoWait],
    [tc.RawI2C(11, 1, 0x68, 200, [1]), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, 'abcd'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, 'telemetry.current'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, '/telemetry.current'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, './telemetry.current'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, 'telemetry.previous'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, '/telemetry.previous'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, './telemetry.previous'), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, 'a' * 192), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, 'a' * 193), Send, WaitMode.NoWait],
    [tc.RemoveFile(11, ''), Send, WaitMode.NoWait],
    [tc.ResetTransmitterTelecommand(), Send, WaitMode.NoWait],
    [tc.SendBeacon(), Send, WaitMode.NoWait],
    [tc.SendPeriodicMessageTelecommand(20), Send, WaitMode.NoWait],
    [tc.SendPeriodicMessageTelecommand(39), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, 3), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, 2), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, 1), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, 0), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, -1), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, -2), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, AdcsMode.Disabled), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, AdcsMode.Stopped), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, AdcsMode.BuiltinDetumbling), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, AdcsMode.ExperimentalDetumbling), Send, WaitMode.NoWait],
    [tc.SetAdcsModeTelecommand(11, AdcsMode.ExperimentalSunpointing), Send, WaitMode.NoWait],
    [tc.SetAntennaDeployment(12, 0), Send, WaitMode.NoWait],
    [tc.SetAntennaDeployment(12, 1), Send, WaitMode.NoWait],
    [tc.SetBitrate(51, 1), Send, WaitMode.Wait],
    [tc.SetBitrate(51, 2), Send, WaitMode.Wait],
    [tc.SetBitrate(51, 3), Send, WaitMode.Wait],
    [tc.SetBitrate(51, 4), Send, WaitMode.Wait],
    [tc.SetBitrate(51, 8), Send, WaitMode.Wait],
    [tc.SetBootSlots(10, 0, 0), Send, WaitMode.Wait],
    [tc.SetBootSlots(10, 1, 2), Send, WaitMode.Wait],
    [tc.SetBootSlots(10, 7, 0x38), Send, WaitMode.Wait],
    [tc.SetBootSlots(10, 0x40, 0x80), Send, WaitMode.Wait],
    [tc.SetBootSlots(10, 0x80, 0x3f), Send, WaitMode.Wait],
    [tc.SetBootSlots(10, 0x0f, 0x38), Send, WaitMode.Wait],
    [tc.SetBuiltinDetumblingBlockMaskTelecommand(10, True), Send, WaitMode.Wait],
    [tc.SetBuiltinDetumblingBlockMaskTelecommand(10, 0), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(2, 137, 7, 3)]), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(2, 137, 7, 3), tc.ErrorCounterConfiguration(2, 100, 7, 3)]), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(14, 137, 7, 3)]), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(2, 7, 7, 3)]), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(2, 7, 2, 3)]), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(2, 7, 0, 3)]), Send, WaitMode.Wait],
    [tc.SetErrorCounterConfig(0x21, [tc.ErrorCounterConfiguration(2, 7, 2, 0)]), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 0, 0, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 0, 1, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 1, 1, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 2, 1, 'a' * 193), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 1, 2, 'a' * 193), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 2, 2, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 40, 2, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 2, 3, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 3, 3, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 40, 3, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 3, 4, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 4, 4, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 5, 4, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 3, 5, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 4, 5, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 5, 5, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 4, 6, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 5, 6, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 6, 6, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetPeriodicMessageTelecommand(11, 4, 7, "We are The Borg"), Send, WaitMode.Wait],
    [tc.SetTimeCorrectionConfig(22, 0, 0), Send, WaitMode.Wait],
    [tc.SetTimeCorrectionConfig(22, 1, 0), Send, WaitMode.Wait],
    [tc.SetTimeCorrectionConfig(22, 0, 1), Send, WaitMode.Wait],
    [tc.SetTimeCorrectionConfig(22, 1, 1), Send, WaitMode.Wait],
    [tc.SetTime(11, datetime.timedelta(minutes = 20)), Send, WaitMode.Wait],
    [tc.SetTime(11, datetime.timedelta(minutes = 40)), Send, WaitMode.Wait],
    [tc.SetTime(11, datetime.timedelta(hours = 4)), Send, WaitMode.Wait],
    [tc.SetTime(11, datetime.timedelta(days = 40)), Send, WaitMode.Wait],
    [tc.StopSailDeployment(11), Send, WaitMode.Wait],
    [tc.WriteProgramPart([], 0, [i for i in range(0, 190, 1)]), SendReceive, WaitMode.NoWait],
    [tc.WriteProgramPart([1], 0, [i for i in range(0, 190, 1)]), SendReceive, WaitMode.NoWait],
    [tc.WriteProgramPart([6], 0, [i for i in range(0, 190, 1)]), SendReceive, WaitMode.NoWait],
    [tc.WriteProgramPart([1, 3], 0, [i for i in range(0, 190, 1)]), SendReceive, WaitMode.NoWait],
    [tc.WriteProgramPart([1, 2, 0, 2], 0, [i for i in range(0, 190, 1)]), SendReceive, WaitMode.NoWait],
    [tc.WriteProgramPart([3, 4, 5], 0, [i for i in range(0, 191, 1)]), SendReceive, WaitMode.NoWait],
    [tc.DownloadFile(2, '', [1]), SendReceive, WaitMode.NoWait],
    [tc.DownloadFile(2, '', [2660]), SendReceive, WaitMode.NoWait],
    [tc.DownloadFile(2, 'a' * 189, [0]), SendReceive, WaitMode.NoWait],
    [tc.DownloadFile(2, 'a' * 100, []), SendReceive, WaitMode.NoWait],
    [tc.DownloadFile(2, 'abcd', [0, 1, 2, 1]), SendReceive, WaitMode.NoWait],
    [tc.DownloadFile(2, 'abcd', [i for i in range(0, 39, 1)]), SendReceive, WaitMode.NoWait],
    [tc.PerformDetumblingExperiment(correlation_id=5, duration=datetime.timedelta(hours=4), sampling_interval=datetime.timedelta(seconds=2)), Send, WaitMode.Wait],
    [tc.PerformDetumblingExperiment(correlation_id=5, duration=datetime.timedelta(hours=0), sampling_interval=datetime.timedelta(seconds=2)), Send, WaitMode.Wait],
    [tc.PerformDetumblingExperiment(correlation_id=5, duration=datetime.timedelta(hours=4), sampling_interval=datetime.timedelta(seconds=0)), Send, WaitMode.Wait],
    [tc.PerformDetumblingExperiment(correlation_id=5, duration=datetime.timedelta(hours=16), sampling_interval=datetime.timedelta(seconds=2)), Send, WaitMode.Wait],
    [tc.ReadMemory(11, 0, 0), Send, WaitMode.Wait],
    [tc.ReadMemory(11, 0xff, 0x10), Send, WaitMode.Wait],
    [tc.ReadMemory(11, 0xff, 0xffff), Send, WaitMode.Wait],
    [tc.ReadMemory(11, 0xffffffff, 0x1), Send, WaitMode.Wait],
    [tc.TakePhotoTelecommand(10, CameraLocation.Wing, PhotoResolution.p128, 29, datetime.timedelta(seconds = 0), "photo.jpg"), SendReceive, WaitMode.NoWait],
    [tc.TakePhotoTelecommand(10, CameraLocation.Wing, PhotoResolution.p128, 30, datetime.timedelta(seconds = 0), "photo.jpg"), SendReceive, WaitMode.NoWait],
    [tc.TakePhotoTelecommand(10, CameraLocation.Wing, PhotoResolution.p128, 29, datetime.timedelta(seconds = 0), ""), SendReceive, WaitMode.NoWait],
    [tc.TakePhotoTelecommand(10, CameraLocation.Wing, PhotoResolution.p128, 29, datetime.timedelta(seconds = 0), "a" * 31), SendReceive, WaitMode.NoWait],
    [tc.EraseFlash(0xBC), SendReceive, WaitMode.NoWait],
    ["Message", Print, WaitMode.NoWait],
    ["Message", Print, WaitMode.Wait],
    [100, Sleep, WaitMode.Wait],
    [100, Sleep, WaitMode.NoWait],
    [tc.GetSunSDataSets(11, 1, 2), SendReceive, WaitMode.NoWait],
    [tc.PerformCameraCommissioningExperiment(11, ''), SendReceive, WaitMode.NoWait],
    [tc.PerformCameraCommissioningExperiment(11, 'a' * 29), SendReceive, WaitMode.NoWait],
    [tc.PerformCameraCommissioningExperiment(11, '1' * 30), SendReceive, WaitMode.NoWait],
    [tc.CopyBootSlots(11, 0, 0), SendReceive, WaitMode.NoWait],
    [tc.CopyBootSlots(11, 0x7, 0x1C), SendReceive, WaitMode.NoWait],
    [tc.CopyBootSlots(11, 0x3f, 0xf), SendReceive, WaitMode.NoWait],
    [tc.CopyBootSlots(11, 0xC0, 0xC0), SendReceive, WaitMode.NoWait],
    [tc.CopyBootSlots(11, 0x7, 0x38), SendReceive, WaitMode.NoWait],
    [tc.FinalizeProgramEntry([0, 1, 2], 128 * 1024, 0, ''), SendReceive, WaitMode.NoWait],
    [tc.FinalizeProgramEntry([0, 1, 2], 128 * 1024, 0, '1' * 31), SendReceive, WaitMode.NoWait],
    [tc.FinalizeProgramEntry([0, 1, 2, 3], 128 * 1024, 0, '1' * 31), SendReceive, WaitMode.NoWait],
    [tc.FinalizeProgramEntry([], 128 * 1024, 0, '1' * 30), SendReceive, WaitMode.NoWait],
    [tc.FinalizeProgramEntry([7], 1024, 0, '1' * 30), SendReceive, WaitMode.NoWait],
    [tc.FinalizeProgramEntry([6], 30 * 1024, 0, '1' * 30), SendReceive, WaitMode.NoWait],
    [tc.PerformSADSExperiment(11), SendReceive, WaitMode.NoWait],
    [tc.PerformSunSExperiment(11, 1, 2, 3, datetime.timedelta(seconds = 4), 5, datetime.timedelta(seconds = 6), ''), SendReceive, WaitMode.NoWait],
    [tc.PerformSunSExperiment(11, 1, 2, 3, datetime.timedelta(seconds = 4), 5, datetime.timedelta(seconds = 6), '1' * 30), SendReceive, WaitMode.NoWait],
    [tc.PerformSunSExperiment(11, 1, 2, 3, datetime.timedelta(seconds = 4), 5, datetime.timedelta(seconds = 6), '1' * 29), SendReceive, WaitMode.NoWait],
    [[tc.SendBeacon(), 3], SendLoop, WaitMode.NoWait],
]
